### ISSUE TITLE
Caci7 et caci15 - à vérifier

### ISSUE THREAD

**Issue by thibwa** [thibwa/investporc#21]
Peux tu vérifier les formules suivantes et vérifier les résultats du business plan.

function caciav7($array, $arrayF)
{
    $ahb = ahb($array, $arrayF);

    if (getValue('financement', $array) == 'Emprunt') {
        $res1 = ((ctd($array) + $ahb) * getValue('ti', $arrayF) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('dem', $arrayF))));
    } else {

        if ((ctd($array) + $ahb) < getValue('fp', $array)) {
            $res1 = ((ctd($array) + $ahb) * getValue('icci', $arrayF) / (1 - pow(1 + getValue('icci', $arrayF), -getValue('dem', $arrayF))));
        } else {
            $res1 = ((getValue('fp', $array)*getValue('icci', $arrayF)) / (1 - pow(1 + getValue('icci', $arrayF), -getValue('dem', $arrayF)))) +
                ((((ctd($array) + $ahb) - getValue('fp', $array)) * getValue('ti', $arrayF)) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('dem', $arrayF))));
        }
    }

    return round($res1, 2);
}

function caci15($array, $arrayF)
{
    $cb = cb($array);
    $ahb = ahb($array, $arrayF);

    if (getValue('ea', $array) == 'NE' || getValue('ea', $array) == 'EEAP') {
        $res2 = ($cb * getValue('ti', $arrayF)) / (1 - pow((1 + getValue('ti', $arrayF)), -getValue('deb', $arrayF)));
    } else {
        $res2 = ($cb * getValue('ti', $arrayF)) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('deb', $arrayF)));

    }

    if ((getValue('fp', $array) - $ahb) > $cb) {
        $res3 = ($cb * getValue('icci', $arrayF)) / (1 - pow(1 + getValue('icci', $arrayF), -getValue('deb', $arrayF)));
    } else {
        if (getValue('ea', $array) == 'NE' || getValue('ea', $array) == 'EEAP') {
            $res4 = ($cb - (getValue('fp', $array) - $ahb)) * getValue('ti', $arrayF) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('deb', $arrayF)));
        } else {
            $res4 = ($cb * getValue('ti', $arrayF)) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('deb', $arrayF)));
        }

        $res3 = ((getValue('fp', $array) - $ahb) * getValue('icci', $arrayF) / (1 - pow(1 + getValue('icci', $arrayF), -getValue('deb', $arrayF)))) + $res4;
    }

    if (getValue('financement', $array) == 'Emprunt') {
        $res1 += $res2;
    } else {
        if ($ahb < getValue('fp', $array)) {
            $res1 += $res3;
        } else {
            $res1 = (($cb * getValue('ti', $arrayF)) / (1 - pow(1 + getValue('ti', $arrayF), -getValue('deb', $arrayF))));
        }
    }
    return round($res1, 2);
}

**Comment by thibwa** [comment]
Peux-tu me donner les différentes conditions ?

Voici comment c'est pour le moment:

Dans la première condition => EA = NE OU EESP
Dans la seconde condition => EA = NE OU EESP
Dans la troisième condition => EA = NE OU EEAP

Correct ?

**Comment by jwavreille** [comment]
condition
1 changer EESP en NESP
2 changer aussi
3 changer EEAP (toujours le premier E mais aussi le A) en NESP

**Comment by thibwa** [comment]
Est-ce correct ?
(https://cloud.githubusercontent.com/assets/6686308/5739179/2fcecc4e-9bf6-11e4-8ada-757d07d447a0.png)

**Comment by servaisvincent** [comment]
Oui c'est ça.
je le testerai dès que la correction sera faite.

**Comment by thibwa** [comment]
Corrigé :+1:

**Comment by servaisvincent** [comment]
résumé des dernières modifications faite ce 16 janvier 2015 :
1. le code est conçu pour les conditions suivante de "ea" : soit "NE", "EEAP" ou "EESP"
donc les modifications ont été faites dans ce sens
2.  changer le "A" surligné en "S"
![a](https://cloud.githubusercontent.com/assets/6768802/5776697/8de1488e-9d8b-11e4-976e-3fda01b2371d.JPG)
3.  
![c](https://cloud.githubusercontent.com/assets/6768802/5776737/0a2cecfe-9d8c-11e4-91f6-39f197f8f1c1.JPG)
4. effacer ce qui est surligné en jaune
![d](https://cloud.githubusercontent.com/assets/6768802/5776755/3fd7121c-9d8c-11e4-9a73-ce3058542d1e.JPG)
c'est correct maintenant
