### ISSUE TITLE
Longueurs treillis et cloture électrique

### ISSUE THREAD

**Issue by jwavreille** [thibwa/investporc#34]
Même exemple mais avec des cabanes et de la prairie...  
Il ne me propose pas les valeurs de longueur (elles sont à zéro)
Si j'encode les valeurs, c'est à l'enter de l'encodage de la seconde qu'il me propose les longueurs calculées?

Pourquoi ?

**Comment by thibwa** [comment]
A tester

**Comment by jwavreille** [comment]
OK
