### ISSUE TITLE
détails prairies

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#35]
pour un calcul en bio avec naissage 30 truie et vente des porcelets au sevrage.
prairie en gestation uniquement, cabanes en maternité et bâtiment existant en gestation.
Le détail du cout des prairies ne s'affiche pas en étape 4 dans formulaire alors que ça devrait être affiché.
Pourtant, après avoir été dans résultats, lorsqu'on reveint dans formulaire, il affiche le détail.

**Comment by thibwa** [comment]
Corrigé :+1:

**Comment by jwavreille** [comment]
OK
