### ISSUE TITLE
cout aliment porcelet

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#36]
![20140929094837099](https://cloud.githubusercontent.com/assets/6768802/4439716/bab32cc2-47bb-11e4-9e38-ae3778142ea5.jpg)
Modification possible de la formule. Voir ligne 214 de la version 11.
à discuter

**Comment by thibwa** [comment]
Corrigé :+1:

**Comment by jwavreille** [comment]
A tester

**Comment by servaisvincent** [comment]
1. lorsque je fais un calcul, il calcul le cout de l'aliment de procelet qui vaut comme si le pdvp=25 alors que j'avais rentré 12 kg.
2. si je veux ensuite changer la productivité des truies (22 à 24), j'appuie sur calcul, le résultat de change pas et ensuite je retourne voir dans formulaire, il est resté sur 22.

**Comment by thibwa** [comment]
Vincent,

peux-tu faire qq tests ?
J'ai ajouté la valeur de pdvp au dessus du résultat (au dessus de "Investissement de cheptel").

De plus, voici la formule du cout de l'aliment pour porcele=

 $ret = 0;
	$pase = 0;
    $nbpoe = nbpoe($array);
	
	if (getValue('commercialisation', $array) == 'Filière porc en plein air')
		$pase = getValue('pasepp', $arrayF);
	else
		$pase = getValue('pasebio', $arrayF);
		
    if (getValue('naissage', $array) == 'Oui') {
        if (getValue('dpn', $array) == 'VPPE') {
			$ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array));
        } else if (getValue('dpn', $array) == 'VTPE') {
            $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
        } else {
            $ret = ((getValue('nbps', $array) * getValue('nbt', $array)) - ($nbpoe * getValue('nbcy', $array))) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array)) * $pase + $nbpoe * getValue('nbcy', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
		}
    }

    return $ret;

**Comment by servaisvincent** [comment]
Salut Thibaut,

 

Tu saurais faire les 3 modifs en rouge ?

 

Je testerai ensuite…

 

Vincent

 

De : thibwa [mailto:notifications@github.com] 
Envoyé : mardi 20 janvier 2015 15:21
À : thibwa/investporc
Cc : servaisvincent
Objet : Re: [investporc] cout aliment porcelet (#36)

 

Vincent,

peux-tu faire qq tests ?
J'ai ajouté la valeur de pdvp au dessus du résultat (au dessus de "Investissement de cheptel").

De plus, voici la formule du cout de l'aliment pour porcele=

$ret = 0;
$pase = 0;
$nbpoe = nbpoe($array);

if (getValue('commercialisation', $array) == 'Filière porc en plein air')
    $pase = getValue('pasepp', $arrayF);
else
    $pase = getValue('pasebio', $arrayF);
 
if (getValue('naissage', $array) == 'Oui') {
    if (getValue('dpn', $array) == 'VPPE VTPE') {
        $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array))* $PASE;
    } else if (getValue('dpn', $array) == 'VTPE EPCF') {
        $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
    } else {
        $ret = ((getValue('nbps', $array) * getValue('nbt', $array)) - ($nbpoe * getValue('nbcy', $array))) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array)) * $pase + $nbpoe * getValue('nbcy', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
    }
}
 
return $ret;

**Comment by thibwa** [comment]
Salut Vincent,

Je ne vois pas de rouge.

**Comment by thibwa** [comment]
Voici la nouvelle formule proposée par Vincent:

$ret = 0;
$pase = 0;
$nbpoe = nbpoe($array);

if (getValue('commercialisation', $array) == 'Filière porc en plein air')
    $pase = getValue('pasepp', $arrayF);
else
    $pase = getValue('pasebio', $arrayF);
 
if (getValue('naissage', $array) == 'Oui') {
    if (getValue('dpn', $array) == 'VTPE') {
        $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array))* $PASE;
    } else if (getValue('dpn', $array) == 'EPCF') {
        $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
    } else {
        $ret = ((getValue('nbps', $array) * getValue('nbt', $array)) - ($nbpoe * getValue('nbcy', $array))) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array)) * $pase + $nbpoe * getValue('nbcy', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
    }
}
 
return $ret;

**Comment by servaisvincent** [comment]
ça marche!
