### ISSUE TITLE
coût alimentaire truies lactation et gestation

### ISSUE THREAD

**Issue by jwavreille** [thibwa/investporc#37]
![image](https://cloud.githubusercontent.com/assets/6763882/5872861/5495bbcc-a2f0-11e4-9012-bc104ef02f50.png)

à corriger comme ceci... (lire le rouge changé avec Vincent aujourd'hui) Merci

![image](https://cloud.githubusercontent.com/assets/6763882/5872825/053e92ec-a2f0-11e4-8233-06b2ad4c2d02.png)

**Comment by thibwa** [comment]
c'est quoi 
jwetvs 23/01/2015 ?

**Comment by thibwa** [comment]
Donc la formule devient = 
function somlacpx($array)
{
    $ret = 0;

    if (getValue('naissage', $array) == 'Oui')
        $ret = (getValue('cjal', $array) * getValue('aps', $array) * getValue('nbcy', $array) * getValue('pal', $array) * (getValue('nbt', $array))) +
            (getValue('cjag', $array) * getValue('nbcy', $array) * 7 * getValue('pal', $array) * getValue('nbt', $array)) +
            ((getValue('cjag', $array) + 1) * getValue('nbcy', $array) * 7 * getValue('pal', $array) * getValue('nbt', $array));

    return $ret;
}

Ok pour toi?

**Comment by thibwa** [comment]
function somgespx($array)
{
    $ret = 0;

    if (getValue('naissage', $array) == 'Oui')
        $ret = getValue('cjag', $array) * (365 - (getValue('nbcy', $array) * (getValue('aps', $array) + 7 + 7))) * 
			getValue('pag', $array) * getValue('nbt', $array) + (getValue('nbv', $array) * 365 * getValue('pag', $array));

    return $ret;
}

Ok pour toi?

**Comment by servaisvincent** [comment]
Les 2 formules me semblent correctes.
jwetvs 23/01/2015 : José Wavreille et Vincent Servais et la date de modification

**Comment by thibwa** [comment]
Les 2 formules sont corrigés.
(C'est le cas depuis ma réponse au ticket)
tu peux tester :)

**Comment by jwavreille** [comment]
Encore une erreur dans la seconde.... à la fin.... la consommation journalière (du verrat) cjag n'est pas dans le terme 

".... + (getValue('nbv', $array) * 365 * getValue('pag', $array));"

il faut l'ajouter dans la multiplication

**Comment by thibwa** [comment]
Donc la formule devient =>

function somgespx($array)
{
    $ret = 0;

    if (getValue('naissage', $array) == 'Oui')
        $ret = getValue('cjag', $array) * (365 - (getValue('nbcy', $array) * (getValue('aps', $array) + 7 + 7))) * 
			getValue('pag', $array) * getValue('nbt', $array) + (getValue('nbv', $array) * 365 * getValue('pag', $array) * getValue('cjag', $array));

    return $ret;
}

Correct ?

**Comment by jwavreille** [comment]
Ok pour la formule, mais...
Essaie de faire un calcu tout simple avec juste de l'élevage... dans lequel tu change la valeur du prix de l'aliment de gestation....   calcul.... et puis tu reprends le formulaire...  le prix de l'aliment de gestation est-il celui que tu as encodé?
Perso...  je n'y arrive pas du premier coup; le prix de l'aliment est celui avant encodage. C'est seulement au second tour que ça marche.

**Comment by thibwa** [comment]
En effet, le problème venait du fait que lorsque l'on choisit l'engraissement (vente à 100%, engraissement d'une partie, ...), les valeurs suivantes étaient recalculées:
paf, pal, pag, pase, pac, pvp, pvpa, Prixdevente

Ces valeurs sont calculées au choix de la commercialisation.
Maintenant je ne pense que ces valeurs doivent être recalculées au choix de l'engraissement.

Qu'en penses tu?

Acutellement, j'ai retiré le recalcul de ces valeurs au choix de l'engraissement.

**Comment by jwavreille** [comment]
Ok ça me paraît beaucoup mieux.
Une vérification avant de fermer.

**Comment by servaisvincent** [comment]
après test, ok pour le coût de l'aliment de gestation et maternité
Mais pour celui de PS, si je change le cout/kg dans le formulaire, le résultat ne se met pas à jour

**Comment by jwavreille** [comment]
Idem pour un calcul avec naissage et engraissement, le cout alimentaire en post-sevrage ne se met pas à jour quand je change le prix de l'aliment

**Comment by thibwa** [comment]
le cout alimentaire en post-sevrage ne se met pas à jour quand je change le prix de l'aliment

Je ne comprends pas ...

Peux-tu me donner les noms des labels stp.

**Comment by jwavreille** [comment]
prix de l'aliment de sevrage ici dans le formulaire...
(pase mais qui peut venir de pasepp ou de pasebio..?)

![image](https://cloud.githubusercontent.com/assets/6763882/5916704/4b146978-a614-11e4-9299-9dbef3bcf02b.png)

et les calculs de 

![image](https://cloud.githubusercontent.com/assets/6763882/5916747/ba7ac2a8-a614-11e4-8d20-8c0c3999962d.png)

**Comment by thibwa** [comment]
En fait, PASE (Prix de l'aliment de sevrage pour porcelets) n'est pas réellement utilisé dans la formule... 

Il prend seulement pasepp ou pasebio.

function sompclpx($array, $arrayF)
{
    $ret = 0;
	$pase = 0;
    $nbpoe = nbpoe($array);
	
	if (getValue('commercialisation', $array) == 'Filière porc en plein air')
		$pase = getValue('pasepp', $arrayF);
	else
		$pase = getValue('pasebio', $arrayF);
		
    if (getValue('naissage', $array) == 'Oui') {
        if (getValue('dpn', $array) == 'VTPE') {
			$ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * 
			(getValue('pdvp', $array) - getValue('pdps', $array)) * $pase;
        } else if (getValue('dpn', $array) == 'EPCF') {
            $ret = getValue('nbps', $array) * getValue('nbt', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
        } else {
            $ret = ((getValue('nbps', $array) * getValue('nbt', $array)) - ($nbpoe * getValue('nbcy', $array))) * getValue('icmoins25', $arrayF) * (getValue('pdvp', $array) - getValue('pdps', $array)) * $pase + $nbpoe * getValue('nbcy', $array) * getValue('icmoins25', $arrayF) * (getValue('pdtpe', $arrayF) - getValue('pdps', $array)) * $pase;
		}
    }

    return $ret;
}

**Comment by servaisvincent** [comment]
Ce n'est pas la même chose pour l'aliment de lactation, gestation,...?

**Comment by jwavreille** [comment]
Ok Thib, pasepp ou pasebio...

Qui peuvent être changer par l'internaute dans le formulaire 
![image](https://cloud.githubusercontent.com/assets/6763882/5946154/ec822ae6-a733-11e4-97af-6fd82812abfa.png)

et alors le "montant des aliments pour porcelets" doit changer!

**Comment by thibwa** [comment]
OK corrigé ! :+1:

**Comment by jwavreille** [comment]
Ok
