### ISSUE TITLE
mise à jour valeur par défaut

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#39]
Je ne parviens pas à modifier la valeur par défaut, il semblerait que je n'ai le choix qu'entre 2 valeurs valides??

![g](https://cloud.githubusercontent.com/assets/6768802/5896616/c997fe04-a538-11e4-8e67-86d1d137f5b0.jpg)

**Comment by thibwa** [comment]
Vincent, 

je viens de corriger ce bug.
La raison => http://www.w3.org/TR/2012/WD-html5-20121025/common-input-element-attributes.html#attr-input-step

**Comment by servaisvincent** [comment]
ok  merci
