### ISSUE TITLE
Mail de récupération de mot de passe

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#40]
J'ai des caractère bizarres dans le mail. Normal? Pas moyen de corriger?
L'origine du mail est alpinisto. Pas possible de changer en Investporc ou un truc du genre?

![h](https://cloud.githubusercontent.com/assets/6768802/5957308/f4919576-a7b7-11e4-9398-28c381bc6552.JPG)

**Comment by servaisvincent** [comment]
Et quand je clique sur le lien, rien ne s'ouvre...

**Comment by thibwa** [comment]
En effet, il pointe vers l'adresse de production. Donc normal.
Je vais changer l'encodage du mail pour éviter les accents.

**Comment by thibwa** [comment]
![image](https://cloud.githubusercontent.com/assets/6686308/6182843/0458dca4-b34c-11e4-8ea8-efa018d6b261.png)
