### ISSUE TITLE
modification d'un calcul

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#41]
après avoir calculer un projet naissage et engraissement, je retourne dans formulaire pour changer le nombre de truies et le nombre de place à l'engraissement, j'appuie à nouveau sur "calcul" et le résultat de change pas. Je retourne alors dans formulaire et les valeur affichées sont celles du calcul initial.

**Comment by thibwa** [comment]
Vincent, tu as trouvé un très gros bug !!!
Maintenant c'est corrigé :)
