### ISSUE TITLE
Clôtures 

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#42]
J'ai fait un test en bio, 10 truies, tout engraissé, gestation et lactation en prairie (0.8 et 0.47 ha).
Mais arrivé dans la partie prairie, les longueurs de treillis et clôtures électriques sont =0 alors qu'il devrait y avoir une longueur
![invest test](https://cloud.githubusercontent.com/assets/6768802/7451545/2ebe5e16-f252-11e4-8f47-13b31f8126bd.JPG)

**Comment by wavreille** [comment]
Ce bug existe aussi dans la version sur "alpinistesarboriciles"!

**Comment by wavreille** [comment]
Ce bug existe aussi dans la version sur alpinistesarboricoles!

**Comment by servaisvincent** [comment]
un problème similaire dans l'issue 34 :
![invest 2](https://cloud.githubusercontent.com/assets/6768802/7454843/e93016fc-f277-11e4-8da2-955178f9c674.JPG)

**Comment by thibwa** [comment]
por les clotures....   en plus du ticket pour que le calcul se fasse, tu pourrais faire en sorte que ces 2 longueurs soient arrondies à la dizaine?

---

Désormais l'ensemble des champs seront recalculés automatiquement. ==> A tester :+1: 
Ensuite, ces 2 champs sont arrondis à la dizaine.

**Comment by servaisvincent** [comment]
Testé sur la version en ligne (2.0?), mais bug toujours existant.
idem sur alpinisteabroricole
Comment accéder à la verrsion 2.1?

**Comment by wavreille** [comment]
... Thibaut ?

**Comment by wavreille** [comment]
Vincent
Il faut que tu détailles l'exemple que tu testes car cela fonctionne pour l'exemple l'exemple que je viens de faire. L'erreur tiendrait aux choix opérés.

**Comment by thibwa** [comment]
Vincent, peux-tu décrire ce que tu as fait exactement pour répéter le bug ?

Je viens de changer le milestone pour 2.0 (c'était une erreur de ma part).

**Comment by servaisvincent** [comment]
voici les captures d'écran faite ce jeudi matin (version beta 2.0?) sur le site "leporcdewallonie":
![cloture1](https://cloud.githubusercontent.com/assets/6768802/7742635/aaedc7a0-ff91-11e4-9665-53e09a0731a7.JPG)
![cloture2](https://cloud.githubusercontent.com/assets/6768802/7742637/ae7f91b4-ff91-11e4-890e-ae818bcec3d8.JPG)
![cloture3](https://cloud.githubusercontent.com/assets/6768802/7742638/ae82760e-ff91-11e4-87b1-faf35ef94190.JPG)
![cloture4](https://cloud.githubusercontent.com/assets/6768802/7742636/ae65f5c4-ff91-11e4-989f-7ce5c6408f25.JPG)

**Comment by thibwa** [comment]
Le problème venait d'une conversion d'un nombre à virgule (type float) vers un nombre entier (type int). Donc 0,28 => 0.

Je viens de corriger le problème, peux-tu controler ?

**Comment by servaisvincent** [comment]
voila ce que j'obtiens en faisant le même calcul:
![lce2](https://cloud.githubusercontent.com/assets/6768802/7813003/71638edc-03b7-11e5-80d4-fdbe4c409b70.JPG)
l'affichage est correct mais la valeur de "lce" trop importante.
Quand je regarde la formule dans excel, le résultat de la formule devrait être 2710 m (ligne 90 dans la capture ci-dessous). D'ailleurs en l'analysant, cette formule devrait, il me semble, être modifié pour correspondre à la formule en dessous (ligne 91 dans la capture ci-dessous) pour donner le résultat de 1970 m.
![lce3](https://cloud.githubusercontent.com/assets/6768802/7813138/9b68f1b2-03b8-11e5-866d-63e57d2a7c04.JPG)

Il s'agit de supprimer ce qui est en rouge dans la ligne 90. Ainsi, la logique de calcul serait la même que pour les autres types d'animaux (ici gestantes) et correspondrait mieux à mes estimations.
à discuter.

**Comment by wavreille** [comment]
Vincent, 
Il faut revoir la fin de la formule car confusion de variable?

**Comment by servaisvincent** [comment]
l'exemple avec 2700 m dans excel est en V14

**Comment by jwavreille** [comment]
![image](https://cloud.githubusercontent.com/assets/6763882/8041962/28d7a576-0e1c-11e5-8009-af4cc88822b0.png)

**Comment by servaisvincent** [comment]
Ne serait-ce pas un problème de parenthèses… ? voir en rouge pour le calcul SPATG

(Je me souviens pourquoi le « +1 » à NbPOE, c’était pour ne pas avoir d’erreur due à une division par zero)


![lce4](https://cloud.githubusercontent.com/assets/6768802/8052351/fe9652ec-0e86-11e5-9c72-d024da0f9a09.JPG)

**Comment by thibwa** [comment]
Corrigé !!! :+1:

**Comment by thibwa** [comment]
function getLce() {
    ret = 0;
    nb = _nbpoe();
    nb_2 = _nbtm();

    if (document.getElementById('naissage').value == 'Oui') {
        ret = (Math.sqrt(parseFloat(document.getElementById('spatm').value) / nb_2) * 2 * 100 * nb_2);

        if (document.getElementById('ceb').value == '4 bandes')
            ret += Math.sqrt(parseFloat(document.getElementById('spatg').value) / parseFloat(document.getElementById('nbt').value) / 4 * 3) * 2 * 100;
        else
            ret += Math.sqrt(parseFloat(document.getElementById('spatg').value) / parseFloat(document.getElementById('nbt').value) / 7 * 4) * 2 * 100;

        if (document.getElementById('ceb').value == '4 bandes') {
            ret *= parseFloat(document.getElementById('nbt').value) / 4 * 3;
        }
        else
            ret *= parseFloat(document.getElementById('nbt').value) / 7 * 4;
    }

    ret += Math.sqrt(parseFloat(document.getElementById('spape').value) / ((nb + 1) / parseFloat(document.getElementById('nbpc').value))) * 2 * 100 * (nb / parseFloat(document.getElementById('nbpc').value));

    document.getElementById('lce').value = Math.round((lt() * 2 + ret));
}
