### ISSUE TITLE
autres bâtiments 

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#43]
lorsque j'encode le montant d'un bâtiment existant, p.ex 20.000 €, comme 20.000 avait déjà été encodé, après le chiffre "2", des propositions apparaissent (derniers encodages commençant par "2"). Si je clique sur un de ces choix, la somme des bâtiments existants = 2
si l'utilisateur n'est pas attentif, ça peut poser problème, sinon, il faut encoder le montant complet.
![invest 3](https://cloud.githubusercontent.com/assets/6768802/7468904/ff186078-f30d-11e4-89a6-e73788859442.JPG)

**Comment by thibwa** [comment]
Corrigé :)

J'ai rajouté un évenement sur les champs "Montant", désormais à chaque fois que tu presses une touche ou que tu quittes le champ, le montant total est recalculé.
