### ISSUE TITLE
valeurs par défaut

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#45]
Après avoir demandé à Marie les chiffres actuels, je me suis permis de modifier 4 valeurs par défaut/question. (voir colonne 13/10/15)
Ok? sinon, je remets l'ancienne valeur...
![capture2](https://cloud.githubusercontent.com/assets/6768802/10456256/b15728c4-71c0-11e5-8798-7eca189a1ceb.JPG)
![capture](https://cloud.githubusercontent.com/assets/6768802/10456255/b13d65d8-71c0-11e5-89cb-019522778466.JPG)

**Comment by jwavreille** [comment]
OK
