### ISSUE TITLE
Ré-initiation

### ISSUE THREAD

**Issue by servaisvincent** [thibwa/investporc#46]
J'ai un petit souci de ré-initiation de ma page et de mes valeurs lors d'un nouveau calcul.
J'appuie sur intitialiser, et mes valeurs déjà encodées précédemment restent.
J'éteinds mon navigateur, je l'ouvre à nouveau, et les valeurs restent également

**Comment by jwavreille** [comment]
Soucis idem sans réinitialiser mais en choissant "calcul" dans le menu du haut

Soucis avec Firefox et chrome MAIS pas avec explorer !!!!

**Comment by jwavreille** [comment]
...  étrange...  de la maison le problème ne se présente pas (ce 14/10).
Comment est-ce possible? Pourrait-il y avoir une explication sur une bande passante très lente au CRA?

**Comment by thibwa** [comment]
Corrigé

**Comment by servaisvincent** [comment]
ok il ré-initilise bien
